### ISSUE TITLE
Hard-coded path

### ISSUE THREAD

**Issue by gauss256** [YUCHEN005/NASE#2]
When running `enhancement.py`, the following error message occurs.

```
FileNotFoundError: [Errno 2] No such file or directory: '/home3/huyuchen/pytorch_workplace/sgmse/BEATs_iter3_plus_AS2M.pt'
```

**Comment by YUCHEN005** [comment]
pls refer to README where the download address is provided.

https://valle.blob.core.windows.net/share/BEATs/BEATs_iter3_plus_AS2M.pt?sv=2020-08-04&st=2023-03-01T07%3A51%3A05Z&se=2033-03-02T07%3A51%3A00Z&sr=c&sp=rl&sig=QJXmSJG9DbMKf48UDIU1MfzIro8HQOf3sqlNXiflY1I%3D

**Comment by gauss256** [comment]
I was able to find the checkpoint. The issue is that the code is looking for a checkpoint in a hard-coded directory: `/home3/huyuchen/pytorch_workplace/sgmse/`. There is no command-line option for `enhancement.py` to specify the location of the BEATs checkpoint, only the `epoch...` checkpoint.

**Comment by YUCHEN005** [comment]
In `enhancement.py`, the `ScoreModel` is initialized from lightning's `load_from_checkpoint` function, which is nontrivial to add customized argument. 

For quick implementation, we directly write the beats path in `ScoreModel`, you can modify it to yours.

**Comment by gauss256** [comment]
The problem is that the `/home3/...` path is embedded in the checkpoint `epoch_97_pesq_3.01.ckpt` so changing the path in the code doesn't solve the problem.

The workaround I've used is to create the path `/home3/huyuchen/pytorch_workplace/sgmse/` on my system and put a symbolic link to the BEATs checkpoint there. It works, but it's not ideal.

**Comment by YUCHEN005** [comment]
Thank you for reporting this, we will try to fix it.

**Comment by gauss256** [comment]
I have created a pull request for a possible solution.
https://github.com/YUCHEN005/NASE/pull/4

**Comment by YUCHEN005** [comment]
Thank you very much for contributes! I have merged it.
