### ISSUE TITLE
How can I download the BEATs.pt in README.txt? The link is invaild

### ISSUE THREAD

**Issue by Johnsonabuse** [YUCHEN005/NASE#6]
-----------------------------------------------------
OK I have saved this problem for download the newer version of numpy.I have downloaded the numpy version of 1.24
The download link of BEATs.pt in README.txt is invalid.Can you provide a renewd download link or use the BEATs.py to generate BEATs.pt? Thank you

**Comment by YUCHEN005** [comment]
Hi, for beats pretrained model you may go to original repo at https://github.com/microsoft/unilm/tree/master/beats
